#!/bin/sh

# This script integrates with the NIT (NUT Integration Testing) framework
# and is used to arrange a temporary custom configuration for the NUT data
# server and some drivers, along with SSL certificates, etc.
#
# Expects `nit.sh` in PATH (see e.g. .github/workflows/04-maven-nit.yml
# which calls this as PATH="`pwd`/nut/tests/NIT:${PATH}" ./test-NIT.sh)
# and is initially geared towards CI runs and developer reproduction on
# similar OS platforms (expected tools, NUT programs in PATH, etc.)
# Do not expect TOO much from NUT binaries, as they can be packaged and
# a decade old.
#
# You can provide NUT_BUILDDIR location to use a custom build of NUT,
# and `export JNUT_TEST_NIT_SUBSHELL=true` to stop this script just after
# starting the drivers and data server, e.g. so you can run the client
# separately in a debugger.
#
# Uses "dumb shell" syntax though, for maximum portability across decades.
#
# NOTE this will (re-)create a "tmp" subdirectory in your current location
# with configuration files generated by NIT and extended by this script.
#
# Copyright
#       2026- Jim Klimov <jimklimov+nut@gmail.com>
#
# License: GPLv2+

# We are specifically interested in seeing the server side of dialogs,
# not so much general NUT_DEBUG_LEVEL that would add noise from drivers:
[ -n "${NUT_DEBUG_LEVEL_UPSD}" ] || NUT_DEBUG_LEVEL_UPSD=6

# Normalize incoming paths, e.g. avoid `~` chars for home-dir builds if we can:
if [ -n "${NUT_BUILDDIR-}" ] ; then
    D="`cd \"${NUT_BUILDDIR}\" && pwd`" && NUT_BUILDDIR="$D"
    [ -n "${NUT_SRCDIR-}" ] || {
        if [ -s "${NUT_BUILDDIR-}/config.log" ] ; then
            NUT_SRCDIR="`grep -E '^ABS_TOP_SRCDIR=' < \"${NUT_BUILDDIR-}/config.log\" | head -1 | sed 's,ABS_TOP_SRCDIR=,,' | tr -d '\"' | tr -d \"'\"`" || NUT_SRCDIR=""
            if [ -n "${NUT_SRCDIR-}" ] && [ -d "${NUT_SRCDIR-}" ] ; then
                echo "[TEST-NIT] Detected NUT_SRCDIR='$NUT_SRCDIR' from the build area in NUT_BUILDDIR='$NUT_BUILDDIR'" >&2
            else
                NUT_SRCDIR=""
            fi
        fi
    }
fi

if [ -n "${NUT_SRCDIR-}" ] ; then
    D="`cd \"${NUT_SRCDIR}\" && pwd`" && NUT_SRCDIR="$D"
fi

[ -n "${NIT_SCRIPT-}" ] || NIT_SCRIPT="`command -v nit.sh`" || {
    NIT_SCRIPT=""
    if [ -n "${NUT_BUILDDIR}" ] && [ -x "${NUT_BUILDDIR}/tests/NIT/nit.sh" ] ; then
        NIT_SCRIPT="${NUT_BUILDDIR}/tests/NIT/nit.sh"
    else
        if [ -n "${NUT_SRCDIR}" ] && [ -x "${NUT_SRCDIR}/tests/NIT/nit.sh" ] ; then
            NIT_SCRIPT="${NUT_SRCDIR}/tests/NIT/nit.sh"
        fi
    fi
}

[ -n "${NIT_SCRIPT}" ] && [ -x "${NIT_SCRIPT}" ] || {
    echo "[ERROR] nit.sh is required, check out NUT sources and provide it via PATH or NIT_SCRIPT envvar!" >&2
    exit 1
}
NIT_SCRIPT_DIR="`dirname \"${NIT_SCRIPT}\"`"
D="`cd \"${NIT_SCRIPTDIR}\" && pwd`" && NIT_SCRIPT_DIR="$D"

[ -n "${TEST_JAR-}" ] || {
    TEST_JAR="`ls -1 ./jNutList/target/jNutList-*-jar-with-dependencies.jar | tail -1`" || {
        TEST_JAR=""
        mvn package || exit
        TEST_JAR="`ls -1 ./jNutList/target/jNutList-*-jar-with-dependencies.jar | tail -1`"
    }
}

[ -n "${TEST_JAR-}" ] && [ -s "${TEST_JAR-}" ] || {
    echo "[ERROR] TEST_JAR not specified or found: ${TEST_JAR}" >&2
    exit 1
}

if [ -n "${NUT_BUILDDIR}" ] && [ -d "${NUT_BUILDDIR}" ] ; then
    PATH="${NUT_BUILDDIR}/clients:${NUT_BUILDDIR}/server:${NUT_BUILDDIR}/drivers:${NUT_BUILDDIR}/tools/nut-scanner:${PATH}"
    [ -n "${NUT_DRVPATH-}" ] || NUT_DRVPATH="${NUT_BUILDDIR}/drivers"
fi

# Ubuntu-ish default PATH setup for installed package; should work with
# other systems though if they just use standard (s)bin dirs.
[ -n "${NUT_DRVPATH-}" ] || {
    for D in /libexec/nut /lib/nut ; do
        [ -d "$D" ] && NUT_DRVPATH="$D"
    done
}

PATH="/usr/sbin:/usr/bin:$JAVA_HOME/bin:$PATH"
if [ -n "${NUT_DRVPATH-}" ] && [ -d "${NUT_DRVPATH-}" ] ; then
    PATH="${NUT_DRVPATH}:$PATH"
fi
export PATH

echo "[TEST-NIT] Calling NIT_SCRIPT='${NIT_SCRIPT}' to prepare the sandbox" >&2
if [ -n "${NUT_BUILDDIR}" ] && [ -d "${NUT_BUILDDIR}" ] ; then
    :
else
    # Hard-coded NSS to match Debian/Ubuntu builds
    WITH_SSL_SERVER=NSS
    WITH_SSL_CLIENT=NSS
    export WITH_SSL_SERVER WITH_SSL_CLIENT
fi

DEBUG_NIT=true
export DEBUG_NIT

DEBUG_SLEEP=1
export DEBUG_SLEEP

#NIT_CASE="generatecfg_upsd_add_SSL && generatecfg_upsdusers_trivial && generatecfg_ups_dummy"
NIT_CASE="generatecfg_sandbox"
export NIT_CASE

${NIT_SCRIPT} || {
    echo "[ERROR] NIT_SCRIPT='${NIT_SCRIPT}' FAILED to prepare the sandbox" >&2
    exit 1
}

echo "[TEST-NIT] NIT_SCRIPT='${NIT_SCRIPT}' prepared the sandbox, sourcing the environment" >&2
if [ -s "${NIT_SCRIPT_DIR}/tmp/etc/NIT.env" ]; then
    . "${NIT_SCRIPT_DIR}/tmp/etc/NIT.env" || exit
else
    . ./tmp/etc/NIT.env || exit
fi

[ -n "$NUT_CONFPATH" ] && [ -d "$NUT_CONFPATH" ] || {
    echo "[ERROR] NUT_CONFPATH was not set or is not a directory! $NUT_CONFPATH" >&2
    exit 1
}

# Note these might have not been on PATH before we sourced the NIT.env
# e.g. if testing against a custom build of NUT:
for TOOL in upsd upsdrvctl ; do
    command -v "$TOOL" || {
        echo "[ERROR] $TOOL is required, provide it via PATH!" >&2
        echo "PATH=$PATH" >&2
        exit 1
    }
done

echo 'maxstartdelay = 30' > "$NUT_CONFPATH/ups.conf.x"
grep -vw maxstartdelay < "$NUT_CONFPATH/ups.conf" >> "$NUT_CONFPATH/ups.conf.x"
mv -f "$NUT_CONFPATH/ups.conf.x" "$NUT_CONFPATH/ups.conf"

if [ -n "${NUT_DRVPATH-}" ] && [ -d "${NUT_DRVPATH-}" ] \
&& ! grep -w driverpath "$NUT_CONFPATH/ups.conf" \
; then
    echo "driverpath = \"${NUT_DRVPATH-}\"" | sed 's,\\,\\\\,g' > "$NUT_CONFPATH/ups.conf.x"
    cat "$NUT_CONFPATH/ups.conf" >> "$NUT_CONFPATH/ups.conf.x"
    mv -f "$NUT_CONFPATH/ups.conf.x" "$NUT_CONFPATH/ups.conf"
fi

SSL_ARGS=""
if [ -d "$NUT_CONFPATH/cert/upsd" ] ; then
    for TOOL in java keytool pk12util ; do
        command -v "$TOOL" || {
            echo "[ERROR] $TOOL is required, provide it via PATH!" >&2
            echo "PATH=$PATH" >&2
            exit 1
        }
    done

    mkdir -p "${NUT_CONFPATH}/cert/jks"
    JNUTKS="${NUT_CONFPATH}/cert/jks/jNut.jks"

    # For client we need Root CA cert (maybe server cert?) and own cert/key (upsmon)
    # and NIT script already leaves (most of) them there as PEM files
    keytool -importcert -noprompt -trustcacerts -keystore "${JNUTKS}" -storetype JKS -storepass "changeit" -alias "${TESTCERT_ROOTCA_NAME}" -file "${TESTCERT_PATH_ROOTCA}/rootca.pem"
    keytool -importcert -noprompt -keystore "${JNUTKS}" -storepass "changeit" -alias "${TESTCERT_SERVER_NAME}" -file "${TESTCERT_PATH_SERVER}/server.crt"

    if [ ! -e "${TESTCERT_PATH_CLIENT}/client.p12" ] ; then
        if [ -s "${TESTCERT_PATH_CLIENT}/client.key" ] && [ -s "${TESTCERT_PATH_CLIENT}/client.crt" ] && command -v openssl ; then
            # Key goes first!
            [ -s "${TESTCERT_PATH_CLIENT}/.pwfile" ] || { echo "${TESTCERT_CLIENT_PASS}" > ${TESTCERT_PATH_CLIENT}/.pwfile; }
            cat "${TESTCERT_PATH_CLIENT}/client.key" "${TESTCERT_PATH_CLIENT}/client.crt" "${TESTCERT_PATH_ROOTCA}/rootca.pem" \
            | openssl pkcs12 -export -password "file:${TESTCERT_PATH_CLIENT}/.pwfile" -name "${TESTCERT_CLIENT_NAME}" -caname "${TESTCERT_ROOTCA_NAME}" -out ${TESTCERT_PATH_CLIENT}/client.p12
        else
            pk12util -o "${TESTCERT_PATH_CLIENT}/client.p12" -n "${TESTCERT_CLIENT_NAME}" -d "${TESTCERT_PATH_CLIENT}" -W "${TESTCERT_CLIENT_PASS}" -K "${TESTCERT_CLIENT_PASS}"
        fi
    fi
    # keytool -importcert -noprompt -keystore "${JNUTKS}" -storepass "changeit" -alias "${TESTCERT_CLIENT_NAME}" -file "${TESTCERT_PATH_CLIENT}/client.crt"
    keytool -importkeystore -srckeystore "${TESTCERT_PATH_CLIENT}/client.p12" -srcstoretype PKCS12 -srcstorepass "${TESTCERT_CLIENT_PASS}" -srckeypass "${TESTCERT_CLIENT_PASS}" -destkeystore "${JNUTKS}" -deststoretype JKS -deststorepass "changeit" -destkeypass "changeit" -srcalias "${TESTCERT_CLIENT_NAME}" -destalias "${TESTCERT_CLIENT_NAME}" -v

    ls -la "${NUT_CONFPATH}/cert/jks/"

    SSL_ARGS="--ssl-jks-path ${JNUTKS} --ssl-jks-pass changeit --ssl-forceSSL 1 --ssl-certVerify 1"
fi

SETVAR_ARGS=""
if [ -n "${TESTPASS_ADMIN}" ]; then
    SETVAR_ARGS="-w --setvar driver.debug 1"
else
    echo "[WARNING] TESTPASS_ADMIN not provided by NIT.env" >&2
fi

UPSD_PID=""
cleanup() {
    RES=$?
    echo "[TEST-NIT] Stopping NUT daemons to finish the sandbox" >&2
    echo "[TEST-NIT] UPSD_PID='$UPSD_PID'" >&2
    if [ -n "${UPSD_PID}" ]; then
        kill $UPSD_PID || pkill upsd
    fi
    upsdrvctl stop
    echo "[TEST-NIT] Stopped NUT daemons to finish the sandbox, exiting: $RES" >&2
    exit $RES
}

trap cleanup 0 1 2 3 15
echo "[TEST-NIT] Starting NUT daemons to prepare the sandbox" >&2
upsdrvctl start || { echo "[WARNING] NUT drivers did not start" >&2 ; sleep 1; }
sleep 1

OLD_NDL="${NUT_DEBUG_LEVEL-}"
if [ -n "$NUT_DEBUG_LEVEL_UPSD" ] ; then
    NUT_DEBUG_LEVEL="$NUT_DEBUG_LEVEL_UPSD"
    export NUT_DEBUG_LEVEL
fi
upsd -FF &
UPSD_PID="$!"
echo "[TEST-NIT] UPSD_PID='$UPSD_PID'" >&2

NUT_DEBUG_LEVEL="${OLD_NDL}"

echo "[TEST-NIT] Sleeping so the server can fully start" >&2
sleep 5
echo "[TEST-NIT] The NUT data server should be listening at 'localhost:${NUT_PORT}' now" >&2

if [ x"$JNUT_TEST_NIT_SUBSHELL" = xtrue ] ; then
    echo "[TEST-NIT] Starting interactive shell with prepared NIT env, exit it to proceed with JAR test:" >&2
    echo "+" java -jar "${TEST_JAR}" $SSL_ARGS $SETVAR_ARGS "localhost" "${NUT_PORT}" "admin" "${TESTPASS_ADMIN}" >&2
    env PS1='<jNut:`pwd`> ' bash --norc -i
fi

echo "[TEST-NIT] Starting jNutList client '${TEST_JAR}' for the test" >&2
RES=0
( set -x ; java -jar "${TEST_JAR}" $SSL_ARGS $SETVAR_ARGS "localhost" "${NUT_PORT}" "admin" "${TESTPASS_ADMIN}" ) || RES=$?

if [ x"$RES" = x0 ] ; then
    echo "[TEST-NIT] jNutList client test finished: $RES" >&2
else
    echo "[ERROR] jNutList client test failed: $RES" >&2
    exit $RES
fi
